[package]
name = "bevy_mod_openxr"
description = "Community crate for OpenXR in Bevy"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["gamedev", "bevy", "Xr", "Vr", "OpenXR"]

[features]
default = ["vulkan", "d3d12", "passthrough"]
vulkan = ["dep:ash"]
d3d12 = ["wgpu/dx12", "wgpu-hal/dx12", "dep:windows", "dep:d3d12"]
passthrough = []

[dev-dependencies]
bevy_xr_utils.path = "../bevy_xr_utils"
bevy = { workspace = true, default-features = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1"
jni = "0.20"

# bevy can't be placed behind target or proc macros won't work properly
[dependencies]
bevy.workspace = true

# all other dependencies are placed under this since on wasm, this crate is completely empty
[target.'cfg(not(target_family = "wasm"))'.dependencies]
openxr = "0.18.0"
thiserror = "1.0.57"
wgpu = "23.0.1"
wgpu-hal = "23.0.1"
bevy_mod_xr = { path = "../bevy_xr", version = "0.1.0" }

ash = { version = "0.38.0", optional = true }

[target.'cfg(target_family = "unix")'.dependencies]
openxr = { version = "0.18.0", features = ["mint"] }
wgpu = { version = "0.20", features = ["vulkan-portability"] }

[target.'cfg(target_family = "windows")'.dependencies]
openxr = { version = "0.18.0", features = ["mint", "static"] }
windows = { version = "0.58.0", optional = true }
d3d12 = { version = "0.20", features = ["libloading"], optional = true }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
